function hB = plugin_board()
    % Board definition
    
    %   Copyright 2022 Yihua Liu
    
    % Construct board object
    hB = hdlcoder.Board;
    
    hB.BoardName    = 'Arty Z7-20';
    
    % FPGA device information
    hB.FPGAVendor   = 'Xilinx';
    hB.FPGAFamily   = 'Zynq';
    hB.FPGADevice   = 'xc7z020';
    hB.FPGAPackage  = 'clg400';
    hB.FPGASpeed    = '-1';
    
    % Tool information
    hB.SupportedTool = {'Xilinx Vivado'};
    
    % FPGA JTAG chain position
    hB.JTAGChainPosition = 2;
    
    %% Add interfaces
    % Standard "External Port" interface
    hB.addExternalPortInterface( ...
        'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});
    
    % Custom board external I/O interface
    hB.addExternalIOInterface( ...
        'InterfaceID',    'LEDs General Purpose', ...
        'InterfaceType',  'OUT', ...
        'PortName',       'LEDs', ...
        'PortWidth',      4, ...
        'FPGAPin',        {'R14', 'P14', 'N16', 'M14'}, ...
        'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});
    
    hB.addExternalIOInterface( ...
         'InterfaceID',    'Push Buttons', ...
         'InterfaceType',  'IN', ...
         'PortName',       'PushButtons', ...
         'PortWidth',      4, ...
         'FPGAPin',        {'D19', 'D20', 'L20', 'L19'}, ...
         'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});
     
     hB.addExternalIOInterface( ...
        'InterfaceID',    'Slide switches ', ...
        'InterfaceType',  'IN', ...
        'PortName',       'SlideSwitches', ...
        'PortWidth',      2, ...
        'FPGAPin',        {'M20', 'M19'}, ...
        'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});
    
    % LocalWords:  Arty Zynq xc Vivado JTAG IOSTANDARD LVCMOS
    